### ISSUE TITLE
Karakurt Onion Page is unreachable

### ISSUE THREAD

**Issue by furkan-enes-polatoglu** [infinitumitlabs/Karakurt-Hacking-Team-CTI#2]
lhxxtrqraokn63f3nubhbjrzxkrgduq3qogp3yr424tkpvh3z7n4kcyd.onion | 104.243.34.214
Karakurt Onion Page is unreachable. Do you have any information?

**Comment by whichbuffer** [comment]
After the publication of this report the Karakurt team try to remove their tracks but way back before our publication we worked with Government entities on USA and Germany (which majority of the servers in there) most possibly this organizations take down the all servers (published on this public repo) that was being used by Karakurt / Conti group for the further investigation. 

The amount of data we gathered from Karakurt/Conti Internal Servers was huge so we shared all our findings with those government entities to help their investigation. You can find my tweet about the take down (https://twitter.com/WhichbufferArda/status/1519401128181612545).
